### ISSUE TITLE
Don't always prompt for how to handle missing compile_command.json

### ISSUE THREAD

**Issue by jclsn** [asmodeus812/coc-sonarlint#1]
Hi, thank you for writing this plugin. Works great. I have one issue though. When I open a C file without a ``compile_commands.json`` being present, I get always prompted, which is annoying. Can you implement a way to turn that off or only print a small notification in the status line?

**Comment by asmodeus812** [comment]
Hi, i think it is possible yes, probably have to write a property to the global config file once you confirm you do not wish to see it anymore to be persistent across sessions. Will look into it.

**Comment by jclsn** [comment]
Thank you!

**Comment by jclsn** [comment]
Btw where did you find the documentation for sonarlint? I am [trying to run it with the vim9-lsp](https://github.com/yegappan/lsp/issues/520), which I am planning to transition to in the future when it matured, but the server is crashing. I would like to debug that somehow.

**Comment by jclsn** [comment]
Oh, I guess it is not using the Language Server Protocol, as it is not listed here https://langserver.org/

**Comment by asmodeus812** [comment]
It certainly is using it, the command you have provided in the lsp repo seems correct too. I am not sure why it would not be picked up, could be something related to the communication channel, i see you are using stdio, which usually should work but play around with that. There are some basic docs in the official repo of sonarlint but most of this extension is lifted from the vscode sonarlint extension.

**Comment by jclsn** [comment]
It is not accepting those two arguments it seems. Works when I run it in the command line though. 

```
Unknown options: '-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000,quiet=y', '-Dsonarlint.telemetry.disabled=true
```
If I leave them out the server doesn't crash but responds

```
Error: Unsupported request message received from the LSP server (sonarlint-ls), message = {'id': '9', 'jsonrpc': '...': 'sonarlint/shouldAnalyseFile', 'params': {'uri': 'file:///home/jan/Workspace/C%2b%2b/constexpr/constexpr.cpp'}}
```

**Comment by jclsn** [comment]
Just realized those are only for debugging. Got output from SonarLint now and updated the issue. Maybe you can make something out of it.
